Metatavu/pakkasmarja-berries-app

- src/js/pakkasmarja-berries-chat-thread.js
- src/scss/pakkasmarja-berries.scss
> Added load animation into message sending

- src/js/pakkasmarja-berries.js
- src/templates/index.pug
> Improved message thread navigations

- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-news.js
- src/js/pakkasmarja-berries.js
> Fixed issue #14

- src/client-templates/chat-thread.pug
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
> Feature #18 thread image

- run-android.sh
- run-browser.sh
- src/client-templates/chat-message.pug
- src/client-templates/chat-question-group-thread.pug
- src/client-templates/question-group.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Feature #20 question groups

- .scss-style.yml
- src/client-templates/chat-message.pug
- src/scss/pakkasmarja-berries.scss
> Added support for displaying manager messages with different style

- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
> Added support for listening incoming threads

- src/js/pakkasmarja-berries-question-groups.js
- src/scss/pakkasmarja-berries.scss
> Added support for question thread images

- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
> Changed question groups to be reloaded on page change

- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
> Changed all imagePaths -> imageUrls

- src/client-templates/chat-question-group-thread.pug
- src/client-templates/chat-thread.pug
- src/client-templates/question-group.pug
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
> Added latest message date into threads and question groups

- .gitignore
- src/js/pakkasmarja-berries-push-notifications.js
- src/js/pakkasmarja-berries.js
- src/templates/index.pug
> Added support for listing push -notifications about newly published news

- package.json
- src/js/pakkasmarja-berries-chat-threads.js
- src/scss/pakkasmarja-berries.scss
> Fixed chat dissappear bug

- config.xml
- src/client-templates/chat-message.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Added support for sending image messages

- config.xml
- package.json
- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-menu.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Added hamburger menu and possibility to logout

- src/templates/index.pug
> Changed title

- src/client-templates/chat-question-group-thread.pug
- src/client-templates/chat-thread.pug
- src/client-templates/news-item.pug
- src/client-templates/question-group.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-news.js
- src/js/pakkasmarja-berries-question-groups.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Feature #42 highlight unread

- src/js/pakkasmarja-berries-chat-thread.js
> Added send message functionality to message send button

- src/scss/pakkasmarja-berries.scss
> Feature #57 content images

- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-news.js
- src/js/pakkasmarja-berries-question-groups.js
- src/scss/pakkasmarja-berries.scss
> Feature #60 new server

- src/js/pakkasmarja-berries-chat-thread.js
- src/scss/pakkasmarja-berries.scss
> Fixed load animation on image messages

- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-news.js
- src/js/pakkasmarja-berries-question-groups.js
> Feature #66 security

- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Camera or gallery

- src/js/pakkasmarja-berries-chat-thread.js
> Wrap images to link tag

- src/client-templates/chat-message.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/scss/pakkasmarja-berries.scss
> Feature #76 message time

- src/client-templates/chat-message.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/scss/pakkasmarja-berries.scss
> Fixed order bug

- src/scss/pakkasmarja-berries.scss
> Fixed menu bugs

- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries.js
Remove zoom from login view
Remove share button from image viewer
Fixed missing client template
fixes #94
> Trigger main view restored only once to avoid unnecessary ws messages

- src/js/pakkasmarja-berries-device-controls.js
> Fixed back button bug

- src/scss/pakkasmarja-berries.scss
> css edits to show whole name

- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-menu.js
- src/js/pakkasmarja-berries-settings-menu.js
- src/templates/index.pug
> Added account link to settings menu

- bower.json
- src/templates/index.pug
> Added polyfill for Object.assign

- bower.json
- merges/ios/css/overrides.css
- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-push-notifications.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Changed chat message inputs to resize to match the height of the text

- config.xml
- merges/browser/css/overrides.css
- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-menu.js
- src/js/pakkasmarja-berries-news.js
- src/js/pakkasmarja-berries-settings-menu.js
- src/js/pakkasmarja-berries.js
- src/templates/index.pug
> Added support for browser version

- package.json
- src/js/pakkasmarja-berries-client.js
> Changed application to close websockets on pause and rejoin on resume

- src/client-templates/chat-question-group-thread.pug
- src/client-templates/chat-thread.pug
- src/client-templates/question-group.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-device-controls.js
- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Feature #116 conversation target

- merges/browser/css/overrides.css
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
- src/js/pakkasmarja-berries.js
> Updated web app

- src/js/pakkasmarja-berries-chat-thread.js
> Fixed bug with questions groups scrolling

- .gitignore
- Gruntfile.js
- bower.json
- config.xml
- package-lock.json
- package.json
- src/api-client/main.js
- src/api-client/package-lock.json
- src/api-client/package.json
- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-menu.js
- src/js/pakkasmarja-berries-profile-menu.js
- src/js/pakkasmarja-berries-rest.js
- src/js/pakkasmarja-berries-settings-menu.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Feature #122 update contact details

- merges/browser/css/overrides.css
> Fixed scrolling in contract view

- src/scss/pakkasmarja-berries.scss
> Hotfix #132 modals stuck

- config.xml
- package-lock.json
- package.json
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
> Hotfix #133 pdf download

- src/js/pakkasmarja-berries-contracts.js
> Hotfix #136 close inappbrowsers after signature

- src/api-client/package-lock.json
- src/api-client/package.json
- src/client-templates/contract-details.pug
- src/client-templates/past-prices-modal.pug
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
> Added support for showing current and past prices

- src/client-templates/pending-contract-list-item.pug
- src/js/pakkasmarja-berries-contracts.js
> Added possibility for farmer to suggest new quantity

- merges/browser/css/overrides.css
- src/client-templates/contract-details.pug
- src/client-templates/contract-terms.pug
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
> Improved ui and ux in contracts view

- src/client-templates/contract-details.pug
- src/js/pakkasmarja-berries-contracts.js
> Added support for quantity and delivery place comments

- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-rest.js
> Refrest access token if it has expired

- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-rest.js
> Added better rest error handling

- src/api-client/package-lock.json
- src/api-client/package.json
- src/client-templates/contract-details.pug
- src/client-templates/pending-contract-list-item.pug
- src/js/pakkasmarja-berries-contracts.js
> Added support for denying contracts

- src/client-templates/active-contract-list-item.pug
- src/client-templates/contract-details.pug
- src/client-templates/pending-contract-list-item.pug
> Prefer item group display name

- src/client-templates/contract-details.pug
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Added contract signing progress indicator

- src/client-templates/contract-details.pug
- src/client-templates/past-contracts-modal.pug
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
> Added button to display past contract amounts

- merges/browser/css/overrides.css
- src/client-templates/contract-details-placeholder.pug
- src/client-templates/contract-details.pug
- src/js/pakkasmarja-berries-contracts.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Added dual column layout to web version

- src/api-client/package-lock.json
- src/api-client/package.json
- src/client-templates/contract-details.pug
- src/client-templates/pending-contract-list-item.pug
- src/js/pakkasmarja-berries-app-config.js
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Added rest of the missing features requested

- src/client-templates/change-password-dialog.pug
- src/js/pakkasmarja-berries-profile-menu.js
- src/js/pakkasmarja-berries-rest.js
> Added support for changing password

- src/client-templates/contract-details.pug
- src/js/pakkasmarja-berries-contracts.js
- src/js/pakkasmarja-berries-rest.js
- src/scss/pakkasmarja-berries.scss
- src/templates/index.pug
> Changes according to changes requested by client

- src/js/pakkasmarja-berries-auth.js
- src/js/pakkasmarja-berries-client.js
- src/js/pakkasmarja-berries.js
> Fixed connecting screen flickering

- bower.json
- build-browser.sh
- package-lock.json
- package.json
- src/js/pakkasmarja-berries-contracts.js
- src/scss/pakkasmarja-berries.scss
browser version needs to be build with provided build-browser.sh script
fixes #174
> Added ie and edge support

- src/templates/index.pug
> Added settings for contract push notifications

- src/js/pakkasmarja-berries.js
- src/templates/index.pug
> Added support for specifying server side options to display contract tab

- src/js/pakkasmarja-berries-push-notifications.js
> Added support for ios push notifications

- src/client-templates/chat-thread.pug
- src/js/pakkasmarja-berries-chat-thread.js
- src/js/pakkasmarja-berries-chat-threads.js
- src/js/pakkasmarja-berries-question-groups.js
> Added support for loading poll answers

- src/js/pakkasmarja-berries-chat-thread.js
- src/scss/pakkasmarja-berries.scss
> Changed poll other input to autogrow
